version: '3.9'

services:
  webapi:
    container_name: ksiazka
    #image: ksiazkaimage3
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      CONNECTION_STRING: "Host=db;Port=5432;Database=Books;Username=postgres;Password=Lebronjames1*"
    hostname: dupa

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: 'Books'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Lebronjames1*'
    ports:
      - "5432:5432"
    hostname: db
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local